### ISSUE TITLE
Create NavBar

### ISSUE THREAD

**Issue by cdhiraj40** [CerritusCodersComm/community-website#1]
As discussed earlier in the Figma design, the navbar will be looking like this. Feel free to add your touch to it!
![image](https://user-images.githubusercontent.com/75211982/190676034-2b74d778-d8df-4233-8b6e-a0835680e5e0.png)

Cerritus Coders Logo: 
![image](https://user-images.githubusercontent.com/75211982/190676299-addb5f13-c8bc-444b-b847-3e0452c46996.png)

Don't forget to make it under the components folder so that it's reusable.

**Comment by Rahilsiddique** [comment]
hey can i work on this issue ??

**Comment by cdhiraj40** [comment]
closed via #4
