### ISSUE TITLE
Action on the navbar button: Join Our Community

### ISSUE THREAD

**Issue by cdhiraj40** [CerritusCodersComm/community-website#25]
**Is your feature request related to a problem? Please describe.**
Currently, there is no action for on-click on the "Join our community" button in the navbar. 

**Describe the solution you'd like**
On clicking on join our community button, it should scroll down to the join our community section.
![image](https://user-images.githubusercontent.com/75211982/197765793-0257cecd-d83a-42e6-bdf7-d15dae110752.png)

**Comment by Anuran12** [comment]
@cdhiraj40  i would like to work on this

**Comment by cdhiraj40** [comment]
> @cdhiraj40 i would like to work on this

sure! Go ahead!

Also, we are running an event along with Hacktoberest called ["Hacking The Hacktoberest"](https://community-website-aek7b80zf-cerrituscoders.vercel.app/events/hacking-the-hacktoberfest). 
You can register for it from [here](https://bit.ly/hacking-the-hacktoberfest) to earn some extra swags. 
Join our community: https://bit.ly/cerritus-coders

**Comment by suraj-mahato360** [comment]
I would like to work on this issue, please assign me

**Comment by cdhiraj40** [comment]
seems like @Anuran12 does not want to work on this, @suraj-mahato360 sure go ahead!!

**Comment by Athi223** [comment]
Hey @cdhiraj40, if no one is up for this, I'd like to take it up!

**Comment by cdhiraj40** [comment]
hey all! This has been solved for a long time. Closing it.
