### ISSUE TITLE
show custom page on click on events, programs and testimonials 

### ISSUE THREAD

**Issue by Rahilsiddique** [CerritusCodersComm/community-website#26]
**Describe the feature**
while clicking on navbar option of events, programs or tetimonials 404 not page is shown

**Describe the solution you'd like**
A page should be presented showing text like "Sorry, currently this page is getting built by the community."

**Screenshots**
![image](https://user-images.githubusercontent.com/75086395/197766513-1a11882d-41de-4724-b699-ad3978cd63de.png)

**Comment by tarunvashishth** [comment]
I would like to work on this, please assign this to me.

**Comment by cdhiraj40** [comment]
> I would like to work on this, please assign this to me.

sure! Assigning you.

Also, we are running an event along with Hacktoberest called ["Hacking The Hacktoberest"](https://community-website-aek7b80zf-cerrituscoders.vercel.app/events/hacking-the-hacktoberfest). 
You can register for it from [here](https://bit.ly/hacking-the-hacktoberfest) to earn some extra swags. 
Join our community: https://bit.ly/cerritus-coders

**Comment by suraj-mahato360** [comment]
I want to work on this issue please assign me this

**Comment by tarunvashishth** [comment]
> > I would like to work on this, please assign this to me.
> 
> sure! Assigning you.
> 
> Also, we are running an event along with Hacktoberest called ["Hacking The Hacktoberest"](https://community-website-aek7b80zf-cerrituscoders.vercel.app/events/hacking-the-hacktoberfest). You can register for it from [here](https://bit.ly/hacking-the-hacktoberfest) to earn some extra swags. Join our community: https://bit.ly/cerritus-coders

sure I will register.

**Comment by tarunvashishth** [comment]
I am getting errors while installing node modules, and after installing them by --force, npm start is not working.

> > I would like to work on this, please assign this to me.
> 
> sure! Assigning you.
> 
> Also, we are running an event along with Hacktoberest called ["Hacking The Hacktoberest"](https://community-website-aek7b80zf-cerrituscoders.vercel.app/events/hacking-the-hacktoberfest). You can register for it from [here](https://bit.ly/hacking-the-hacktoberfest) to earn some extra swags. Join our community: https://bit.ly/cerritus-coders

**Comment by tarunvashishth** [comment]
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: cerritus-coders@0.1.0
npm ERR! Found: react@17.0.2
npm ERR! node_modules/react
npm ERR!   react@"17.0.2" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^18.1.0" from react-chrono@1.19.2
npm ERR! node_modules/react-chrono
npm ERR!   react-chrono@"^1.19.1" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR! 
npm ERR! See C:\Users\tarun\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\tarun\AppData\Local\npm-cache_logs\2022-10-26T08_05_13_563Z-debug-0.log

**Comment by cdhiraj40** [comment]
The errors have been solved, thanks to the community(discord server).

**Comment by cdhiraj40** [comment]
solved via [#25](https://github.com/CerritusCodersComm/community-website/pull/27)
