### ISSUE TITLE
Create About us section 

### ISSUE THREAD

**Issue by ishir21** [CerritusCodersComm/community-website#6]
![image](https://user-images.githubusercontent.com/91480925/191307201-fe1fc6e1-a17c-4996-8ee8-9d354761fc7d.png)

The below file is the svg to be used in this section.
Do refer the figma file for all the details.

![about](https://user-images.githubusercontent.com/91480925/191307352-7a20a0ff-8262-46db-a3a8-b92c69cdeaee.svg)

**Comment by Rahilsiddique** [comment]
hey, im taking this issue
